# Author: @yarkhinephyo

app: mateo-backend

service: mateo-backend-loan-history-database

provider:
  name: aws
  stage: dev
  region: ap-southeast-1
  lambdaHashingVersion: 20201221

resources:
  Resources:
    UserTransactionDataTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: '${self:service}-${self:custom.stage}'

    # Keep in the AWS Parameter Store for other services to discover
    SSMParameterRouteDataTableArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:custom.stage}/dynamodb/user_transaction/arn
        Type: String
        Value:
          Fn::GetAtt:
            - UserTransactionDataTable
            - Arn
        Tags:
          Environment: ${self:custom.stage}
    SSMParameterRouteDataTableName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:custom.stage}/dynamodb/user_transaction/name
        Type: String
        Value: ${self:resources.Resources.UserTransactionDataTable.Properties.TableName}
        Tags:
          Environment: ${self:custom.stage}

custom:
  stage: ${opt:stage, self:provider.stage}
